<Project Sdk="Aspire.AppHost.Sdk/13.4.3">

  <ItemGroup>
    <ProjectReference Include="..\CheatsheetApp.Api\CheatsheetApp.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.3" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>97015d68-68b7-4835-9370-57137d928355</UserSecretsId>
  </PropertyGroup>

</Project>
